package Lottery;

/**
 * Created by Marco on 10.06.2014.
 */
public enum WinningType {
    FIVE_WITH_TWO_STARS,
    FIVE_WITH_ONE_STAR,
    FIVE_WITH_ZERO_STARS,
    FOUR_WITH_TWO_STARS,
    FOUR_WITH_ONE_STAR,
    FOUR_WITH_ZERO_STARS,
    THREE_WITH_TWO_STARS,
    THREE_WITH_ONE_STAR,
    THREE_WITH_ZERO_STARS,
    TWO_WITH_TWO_STARS,
    TWO_WITH_ONE_STAR,
    TWO_WITH_ZERO_STARS,
    ONE_WITH_TWO_STARS,
    ONE_SUPER_STAR,
    TWO_SUPER_STAR,
    THREE_SUPER_STAR,
    FOUR_SUPER_STAR,
    FIVE_SUPER_STAR
}
